version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "07:00"
      timezone: "Europe/Warsaw"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
    groups:
      npm-minor-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "07:00"
      timezone: "Europe/Warsaw"
    labels:
      - "dependencies"
    commit-message:
      prefix: "docker"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "07:00"
      timezone: "Europe/Warsaw"
    labels:
      - "dependencies"
    commit-message:
      prefix: "ci"
    groups:
      actions-all:
        update-types:
          - "minor"
          - "patch"
